<?php 
/* 
  Template Name:Terms
*/
 ?>
<?php get_header(); ?>
<div id="FAQhero" class='container'>
		<a id='top'>
		<div class='row'>
			<h1 class='col-sm-12'>TERMS AND CONDITIONS</h1>
		</div>
		<div  class='row'>


			<!-- CONTENT -->
			<div class='col-sm-12'>

				<a class="anchor_item colelem" id="generaloverview"></a>
				<dl>
					<dt>This is not  an agreement between you and the City of Detroit.</dt>
					<dd>
						<p>These Terms of Use (“Agreement”) sets forth a legally binding agreement between you and Passport, Inc. (“Company”).  This web site or application, including any software (including, without limitation, software, code, files, images, contained in or generated by the software, accompanying data, Boot ROM code and other embedded software), documentation and any accompanying fonts (collectively, the “Platform”) is provided pursuant to this Agreement. By accessing this Platform in any way, including, without limitation, browsing this Platform, using any information, and/or submitting information to Company, you agree to and are bound by the terms, conditions, policies and notices contained in this Agreement), including, but not limited to, conducting this transaction electronically, disclaimers of warranties, damage and remedy exclusions and limitations, and a choice of North Carolina law. Please read this Agreement carefully before using this Platform.</p>
					</dd>
					<dt>From time to time we may update this Platform and this Agreement</dt>
					<dd>
						<p>Your use of this Platform after we post any changes to this Agreement constitutes your agreement to those changes.  You agree to review this Agreement periodically to ensure that you are familiar with the most recent version.  Company may, in its sole discretion, and at any time, discontinue this Platform or any part thereof, with or without notice, or may prevent your use of this Platform with or without notice to you.  You agree that you do not have any rights in this Platform and Company will have no liability to you if this Platform is discontinued or your ability to access the Platform is terminated. You further agree that Company will not be liable for any modification or suspension of the Platform.</p>	
					</dd>
					<dt>Please read this Agreement carefully before using the Platform.</dt>
					<dd>
						<p>If you do not agree to the terms contained in this Agreement, then you may not use the Platform. Your use of the Platform constitutes your acknowledgment that you have the legal authority to bind yourself or any party you represent to, and your acceptance of, this Agreement.  You acknowledge that you have read and agree to be bound by this Agreement and to comply with all applicable laws, regulations and/or rules with regard to your use of the Platform.  You represent that you have the legal authority to bind yourself or any party you represent to this Agreement.</p>					
					</dd>
					<dt>YOU MAY NOT USE THE PLATFORM FOR ANY PURPOSE THAT IS UNLAWFUL OR PROHIBITED BY THIS AGREEMENT.  YOUR ACCESS TO THE PLATFORM MAY BE TERMINATED IMMEDIATELY IN COMPANY’S SOLE DISCRETION, WITH OR WITHOUT NOTICE, IF YOU FAIL TO COMPLY WITH ANY PROVISIONS OF THIS AGREEMENT AND/OR ADDITIONAL TERMS, OR FOR ANY OTHER REASON, OR NO REASON.</dt>
					<dd>
						<p>On certain areas of this Platform, you may be given the ability to provide us with personally identifiable information. Please read our Privacy Policy for more information about our information collection and use practices.</p>
					</dd>
					<dt>Grant of License</dt>
					<dd>
						<p>The Platform is licensed to you by Company subject to the terms of this Agreement. Neither title nor any intellectual property rights are transferred to you, but rather remain with Company or its licensors, who own full and complete title, and Company and respective licensors reserve all rights not expressly granted to you. The rights granted herein are non-transferable, and are limited to Company’s intellectual property rights in the Platform and do not include any other patents or intellectual property rights.  This Agreement does not grant you any rights to use Company proprietary interfaces and other intellectual property in the design, development, manufacture, licensing or distribution of third-party devices and accessories for use with the Platform.  Any use of the Platform in any manner not allowed under this Agreement is prohibited.  This Agreement does not entitle you to receive and does not obligate Company to provide hard-copy documentation, support, telephone assistance, or enhancements or updates to the Platform</p>
						<p>You may not modify, alter, copy, publicly display or perform, distribute, create derivative works, of the Platform.</p>
						<o>Your rights under this Agreement will terminate automatically without notice from Company if you fail to comply with any term(s) of this Agreement. Upon the termination of this Agreement, you shall cease all use of the Platform and delete all copies of the Platform from your mobile device and account.</o>
					</dd>
					<dt>Company Content</dt>
					<dd>
						<p>Company provides this Platform to you, subject to this Agreement</p>
						<p>This Platform, and any services performed, provided or enabled by or through this Platform and all the information, communications, scripting, photos, text, video, graphics, music, sounds, images, trademarks, logos, product and program names, and other materials and complications of the foregoing, that may be provided to you via this Platform (collectively “Content”) by Company or its content providers, are the property of Company and its content providers, and is protected in the U.S. and internationally under trademark, copyright, and other intellectual property laws, and are intended for the lawful use by registered users (as applicable) of this Platform.  You represent and warrant that you will use the Platform and Content only for the purposes permitted herein, that all information you submit is accurate and otherwise complies with this Agreement, and that you will promptly notify Company if any of your information changes.  Company makes no representation that the Platform or Content are appropriate or available for use in particular locations.</p>
						<p>You agree not to download, display or use any Content in any other manner that is likely to cause confusion among consumers, that disparages or discredits Company and/or its licensors, that dilutes the strength of Company or its licensors’ property, or that otherwise infringes Company or its licensors’ intellectual property rights.</p>
					</dd>
					<dt>Accounts, Security, Passwords</dt>
					<dd>
						<p>Certain areas of the Platform may require registration or may otherwise ask you to provide information to participate in certain features or access certain content. If you elect not to provide such information, you may not be able to access certain content or participate in certain features of the Platform.</p>
						<p>Where the Platform requires you to open an account or otherwise submit information, you must complete the specified process by providing us with current, complete, and accurate information as requested by the applicable registration form. It is your responsibility to maintain the currency, completeness, and accuracy of your registration data,  including, without limitation, your name, address, license plate number, mobile telephone number, business details (if relevant), email address and method of payment details. After you have fully completed the registration form, you may be asked to choose a password and a user name. It is entirely your responsibility to maintain the confidentiality of your password and account. Additionally, you are entirely responsible for any and all activities that occur under your account. You agree to notify Company immediately of any unauthorized use of your account. You further agree not to email, post, or otherwise disseminate any user ID, password, PIN, or other information which provides you access to the Platform.  Company is not liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge.</p>
						<p>You agree that Company may collect and use technical and usage data and related information in compliance with our Privacy Policy. You grant Company the permission to use this information to improve its products or to provide services or technologies to you.</p>
					</dd>
					<dt>Use of Parking Payment Services</dt>
					<dd>
						<p>You activate the parking payment services (“Parking Services”) by either: (a) using the PassportParking mobile app, (b) calling a phone number provided on Company signage or (c) accessing our website at GoPassport.com either on your desktop or mobile browser.</p>
						<p>You are responsible for correctly entering the relevant parking zone number, which is indicated on the sign on the same side of the street and on the same block where your vehicle is parked. The parking zone number informs us of the rate to charge you for your parking and of any time restrictions on the amount of time you are permitted to park your vehicle in that zone. You are responsible for checking and verifying the side of the street and the block on which are parked for any permanent or temporary parking restrictions posted. Note that use of the Parking Services does not guarantee you a parking space and you may only activate the Parking Services after you have found an available space.</p>
						<p>All notices and signs or directions made by relevant government authorities, traffic attendants or authorized persons (e.g., the suspension of a parking space) shall take precedence over any information that you receive from Company if for any reason the information is inconsistent. All applicable parking regulations apply to you and your use of the Parking Services does not exempt you from following such rules. Parking rates may be subject to change and it is your responsibility to ensure that you are paying at the then current parking rate. You agree to pay all fees for Parking Services provided to you pursuant to this Agreement. Company shall process the parking fee from the funds available in your pre-funded account and/or charging your stored method of payment to replenish your account funds at the time of your parking transaction. You must have a valid method of payment registered and sufficient funds in your pre-funded account, or suspension of Parking Services may occur.</p>
						<p>You know that Company has validly accepted your parking transaction when you have received confirmation. You are responsible for ensuring that you have properly activated the Parking Services for the relevant parking zone before you leave your vehicle unattended. You are responsible for any fine, ticket, or penalty charge issued between the time of parking the vehicle and the notification via mobile telephone or Internet that the vehicle is validly parked.</p>
						<p>In the event that the Platform is unavailable, you are not excused from paying for parking for time spent in the associated parking stall and facility.</p>
						<p>Company is not responsible for any fines, parking tickets, penalty notices and the enforcement of vehicle parking related offenses you incur or receive regardless of whether or not you receive any notification via the Platform that the vehicle is validly parked. You are solely responsible for resolving with the relevant authorities any issues that you may have regarding the issuance of fines, parking tickets, penalty notices or your vehicle being impounded. If you authorize Company to contact the relevant authorities on your behalf regarding the issuance of fines, parking tickets or penalty notices, you acknowledge and agree that in such cases, Company may provide all or a portion of your information collected by Company to the relevant authorities. In addition, in the event that you fail to pay any amounts owing for the Parking Services (whether due to a declined credit card or other circumstances), then Company, upon the reasonable request of the relevant authorities, may provide all or a portion of your information collected by Company to such authorities, which you acknowledge and agree that they may use solely for purposes of collecting or attempting to collect any unpaid amounts owed by you.</p>
						<p>If you do not use the Platform account for 2 years, Company may close your account. If your account is closed for any reason including for inactivity, Company will refund any remaining balance after all pending parking transactions are cleared to the payment method on file at the time. In the event a refund cannot be refunded to the payment method, you must contact Company for alternative ways to receive any applicable refund. Please allow up to 6 weeks for refunds to be processed.</p>
					</dd>
					<dt>Use of the Platform</dt>
					<dd>
						<p>The following requirements apply to your use of the Platform:</p>
						<ul>
							<li>You will not use any electronic communication feature of the Platform for any purpose that is unlawful, tortious, abusive, intrusive on another’s privacy, harassing, libelous, defamatory, embarrassing, obscene, threatening, or hateful.</li>
							<li>You will not use the Platform for any commercial purpose not expressly approved by Company in writing.</li>
							<li>You will not upload or otherwise transmit any material that contains viruses or any other computer code, files, or programs which might interrupt, limit, or interfere with the functionality of any computer software or hardware or telecommunications equipment.</li>
							<li>You will not rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or otherwise make available the Platform or any features or functionality of the Platform, to any third party for any reason, including by making the Platform available on a network where it is capable of being accessed by more than one device at any time</li>
							<li>You will not make the Platform available over a network where it could be used on multiple devices at the same time.</li>
							<li>You will not remove, delete, alter or obscure any trademarks or any copyright, trademark, patent or other intellectual property or proprietary rights notices from the Platform, including any copy thereof.</li>
							<li>You will not collect or store personal data about other users.</li>
							<li>Except as and only to the extent permitted by applicable law, you may not copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Platform or any part thereof.  Any attempt to do so is a violation of the rights of Company and its licensors of the Platform. If you breach this restriction, you may be subject to prosecution and damages. By storing content on your device, you are making a digital copy. In some jurisdictions, it is unlawful to make digital copies without prior permission from the rights holder.</li>
						</ul>
					</dd>
					<dt>Intellectual Property Ownership</dt>
					<dd>
						<p>There are a number of trademarks, logos, service marks, slogans, product names and designations and other proprietary indicia (collectively “Trademarks”) used in the Platform and in the Content.  By making these Trademarks available through the Platform and in the Content, Company is not granting you a license to use them in any fashion, and you are not granted any license under any of Company’s or any third party's Trademarks or other intellectual property rights, except as specifically set forth in this Agreement.  No Company Trademarks may be used as a username, icon, identifier, hyperlink or in any other manner without Company’s prior written permission.</p>			
						<p>The Platform, Content, and the selection, coordination, and arrangement thereof, is owned either by Company, or its respective licensors.  The unauthorized copying, displaying, selling, distributing or other use of any Content or Platform is a violation of the law. You acknowledge having been advised by Company that the Content and Platform is protected in the U.S. and internationally by a variety of laws, including but not limited to, copyright laws and treaty provisions, trademark laws, patent laws and other intellectual property and proprietary rights laws.</p>		
					</dd>
					<dt>Representations, Disclaimer of Warranties, and Limitations of Liability</dt>
					<dd>
						<p>Company and its parents, subsidiaries, officers, employees, and contractors and each of their officers, employees and agents (collectively, “Company Affiliates”) make no representation or warranty whatsoever regarding the completeness, accuracy, timeliness or adequacy of any information, facts, views, opinions, statements or recommendations contained on the Platform.  Reference to any product, process, publication or service of any third party by trade name, domain name, trademark, service mark, logo, manufacturer or otherwise does not constitute or imply its endorsement or recommendation by Company or the Company Affiliates.</p>
						<p>The Internet may be subject to breaches of security. Company and the Company Affiliates are not responsible for any resulting damage to any user’s device or computer from any such security breach, or from any virus, bugs, tampering, unauthorized intervention, fraud, error, omission, interruption, deletion, defect, delay in operation or transmission, computer line failure or any other technical or other malfunction. You should also be aware that e-mail and other submissions over the Internet may not be secure, and you should consider this before e-mailing Company or the Company Affiliates any information or posting information to the Platform. Company and the Company Affiliates make no representation or warranty whatsoever regarding the suitability, functionality, performance, availability or operation of the Platform. This Platform may be temporarily unavailable due to maintenance or malfunction of computer equipment.</p>
						<dd>THE PLATFORM (INCLUDING ALL APPLICATION PLATFORM UPDATES) AND THE CONTENT ARE MADE AVAILABLE ON AN “AS IS,” “AS AVAILABLE” AND “WITH ALL FAULTS” BASIS. COMPANY AND THE COMPANY AFFILIATES SPECIFICALLY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, QUALITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, WITH RESPECT TO THE PLATFORM AND THE CONTENT.  COMPANY DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN OR SERVICES PERFORMED, PROVIDED OR ENABLED BY OR THROUGH THE PLATFORM (INCLUDING ANY APPLICATION PLATFORM UPDATES) WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE PLATFORM, (INCLUDING ANY APPLICATION PLATFORM UPDATES) WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE PLATFORM (INCLUDING ANY APPLICATION PLATFORM UPDATES) WILL BE CORRECTED.  No oral or written information or advice given by Company or an authorized representative shall be deemed to alter this disclaimer of warranty, or to create any warranty. Should the Platform prove defective, you assume the entire cost of all necessary servicing, repair or correction.
						<p>YOU AGREE THAT COMPANY AND THE COMPANY AFFILIATES ARE NOT LIABLE TO YOU FOR DAMAGES OF ANY KIND, WHETHER BASED IN TORT, CONTRACT, STRICT LIABILITY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM., EVEN IF COMPANY OR THE COMPANY AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
						<p>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF CERTAIN WARRANTIES AND CONDITIONS, OR THE DISCLAIMER OF SOME TYPES OF DAMAGES, SO SOME OF THE ABOVE MAY NOT APPLY TO YOU.</p>
						<p>BY ACCESSING THIS PLATFORM, REGISTERING WITH THE PLATFORM AND/OR ACCEPTING ANY INFORMATION FROM THIS PLATFORM YOU AGREE TO INDEMNIFY, DEFEND AND HOLD COMPANY AND THE COMPANY AFFILIATES HARMLESS FROM AND AGAINST ANY ACTUAL OR ALLEGED CLAIMS, DEMANDS, CAUSES OF ACTION, JUDGMENTS, DAMAGES, LOSSES, LIABILITIES, AND ALL COSTS AND EXPENSES OF DEFENSE (INCLUDING REASONABLE ATTORNEYS’ FEES AND COURT COSTS) ARISING OUT OF OR RELATING TO: (A) YOUR BREACH OF THIS AGREEMENT; (B) YOUR VIOLATION OF ANY LOCAL, STATE, FEDERAL OR INTERNATIONAL LAW, RULE OR REGULATION; (C) ANY MISREPRESENTATION MADE BY YOU; (D) THE THEFT, MISAPPROPRIATION OR DISCLOSURE OF YOUR USERNAME/PASSWORD/PIN; (E) YOUR AUTHORIZATION OF ANYONE ELSE TO USE YOUR PASSWORD. YOU WILL COOPERATE AS FULLY AND AS REASONABLY REQUIRED IN COMPANY’S DEFENSE OF ANY CLAIM. COMPANY RESERVES THE RIGHT, AT ITS OWN EXPENSE, TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU, AND YOU SHALL NOT, IN ANY EVENT, SETTLE ANY MATTER WITHOUT THE WRITTEN CONSENT OF COMPANY.</p>
					</dd>
					<dt>Mobile Service, Text Message, Internet and Service Fees</dt>
					<dd>
						<p>The use of the Platform may require use of a mobile device and phone service, wireless mobile data service, and text messaging capability, which must be obtained from your wireless carrier, and may require Internet access, which must be obtained from your service provider; you are responsible for obtaining and paying for such additional services and obtaining a suitable device, including without limitation all usage charges related thereto.  You may be required to send and receive, at your cost, electronic communications related to the Platform, including without limitation, administrative messages, service announcements, and diagnostic data reports, from Company, your mobile carrier or third party service providers.</p>
						<p>If you agree to receive text messages from the Platform, the frequency of messages will vary based on your parking activity. Certain texts are required to use the Platform, including verification texts. Message and data rates may apply from your mobile carrier. By providing your consent to participate in this program, you approve any such charges from your mobile carrier. If you do not have an unlimited wireless mobile data plan or text messaging capability, you may incur additional charges from your wireless service in connection with your use of the Platform.  You are solely responsible for obtaining any additional subscription or connectivity services or equipment necessary to access the Platform, including but not limited to payment of all third party fees associated therewith, including fees for information sent to or through the Platform.</p>
						<p>The Platform may not work with all devices or all mobile carriers.  Company makes no representations that the Platform will be compatible with or provided by all mobile carriers.  In the event that fees are charged for the Platform, or other third party service providers charge a fee for the products or services they provide, you agree to pay such fee to the respective party in exchange for your continued use of such products or services.  Some services may be subject to different or additional terms (including fees), which you will be required to agree to prior to your use of such services.</p>
						<p>The information in any Platform message may be subject to certain time lags and/or delays. You are responsible for managing the types of SMS texts you receive. If you have any questions or need help, text HELP to the phone number provided on Company signage. You can deactivate your account at any time at <a href="http://www.gopassport.com">www.gopassport.com.
					</dd>
					<dt>Users of the Apple Platform</dt>
					<dd>
						<p>If you download and use the iOS Platform: You, the end-user of the Platform, acknowledge that the Agreement is entered into by and between Company and you and not with Apple, Inc.  Notwithstanding the foregoing, you acknowledge that Apple, Inc. and its subsidiaries are third-party beneficiaries of this Agreement and that Apple, Inc. has the right (and is deemed to have accepted the right) to enforce this Agreement.  You acknowledge that Apple, Inc. has no obligation whatsoever to furnish any maintenance and support services with respect to the Platform.  You acknowledge that you have reviewed the App Store Terms and Conditions (located online at <a href="http://www.apple.com/legal/itunes/us/terms.html#APPS">http://www.apple.com/legal/itunes/us/terms.html#APPS</a>).  This Agreement incorporates by reference the Licensed Application End User License Agreement (the “LAEULA”) published by Apple, Inc. (located online at <a href="http://www.apple.com/legal/itunes/appstore/dev/stdeula/">http://www.apple.com/legal/itunes/appstore/dev/stdeula/</a>).  For purposes of this Agreement, the Platform is considered the “Licensed Application” as defined in the LAEULA and Company is considered the “Application Provider” as defined in the LAEULA.  If any terms of this Agreement conflict with the terms of the LAEULA, the terms of this Agreement shall control. You further acknowledge and agree that in no event will Apple, Inc. be responsible for any claims relating to the Platform (including, without limitation, a third party claim that the Platform infringes that third party’s intellectual property rights) or your use or possession of the Platform, including but not limited to: (i) product liability claims; (ii) any claim that the Platform fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</p>
					</dd>
					<dt>Links to Third-Party Websites, Applications, and Services</dt>
					<dd>
						<p>The Platform may provide connectivity or links to other third-party services, websites, applications, software, and other content from third-party providers such as social media partners, wireless carriers, and third-party software application developers (“Third-Party Services”).  The Platform may allow you to add/configure certain Third-Party Services to your device.  Company has no control over, makes no representations or warranties whatsoever about any of the Third-Party Services that you may access, is not responsible for the availability of such Third-Party Services, and does not endorse nor is responsible or liable for any content or other materials on or available from such Third-Party Services.  Your use of the Third-Party Services may be subject to additional terms, including software license terms, of those third parties.</p>
						<p>Users who utilize the Third-Party Services should be aware that account and other personal information held by those third parties may be transmitted through and stored on Company servers and/or applications located in the United States and elsewhere.  You understand and agree that the companies that provide the Third-Party Services may access, use and share certain information about you, if you use the Third-Party Services.  You understand and agree Company is not responsible for these companies, or their use of any other of your information.  Your use of the Third-Party Services is at your own risk.</p>
					</dd>
					<dt>Assignment</dt>
					<dd>Company may assign this Agreement in whole or in part, at any time with or without notice to you. You may not assign this contract, or any part of it, to any other person. Any attempt by you to do so is void. You may not transfer to anyone else, either temporarily or permanently, any rights to use all or any part of the Platform.  To the extent that you allow a third party to use your device, you shall remain solely responsible for the use of the Platform by others using the device.</dd>
					<dt>General Information</dt>
					<dd>
						<p>You may also be subject to additional terms and conditions (including, but not limited to, terms and conditions from your wireless carrier or operator) that may apply to your use of the Platform.  If any provision of this Agreement is held to be invalid by any law, rule, order or regulation of any government or by the final determination of any state or federal court, such invalidity shall not affect the enforceability of any other provision of this Agreement. The failure of Company to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision.</p>
						<p>By using the Platform, you agree that the statutes and laws of the United States and the State of North Carolina without regard to conflicts of laws principles, will apply to all matters relating to use of the Platform and the Services, and you agree that any litigation shall be subject to the exclusive jurisdiction of the state or federal courts in Wake County, North Carolina, USA.  The United Nations Convention on Contracts for the International Sale of Goods (1980) is hereby excluded in its entirety from application to this Agreement.  You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Platform or this Agreement must be filed within one (1) year after such claim or cause of action arose or be forever barred. You further agree that any disputes, claims and causes of action arising out of or connected with the Platform and/or this Agreement, will be resolved individually, without resort to any form of class action. The section titles in this Agreement are for convenience only and have no legal or contractual effect.This is not  an agreement between you and the City of Detroit.</p>
						<p>In the event of a complaint or concern regarding this Agreement or the Platform, or for more information, please contact  Company at <a href="tel:704-837-8066">704-837-8066</a> or <a href="mailto:info@gopassport.com">info@gopassport.com.</a></p>
					</dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>


				<a id='rates'></a>
				<h2>Rates & Fees</h2>
				<dl>
					<dt>What are the hourly parking rates?</dt>
					<dd>
						<p>Depending on where you are located, hourly parking rates in most Detroit street parking regions where ParkDetroit is available may be $1.00 per hour, $1.50 per hour or $2.00 per hour. There are signs posted in parking locations with rate information and information on parking regulations and restrictions.</p></dd>
					<dt>Are there additional charges besides the parking rate?</dt>
					<dd>
						<p>When parking time is purchased through ParkDetroit, a convenience fee of 15 cents is charged for each and every transaction. ParkDetroit will inform you of the convenience fee and you will be asked to confirm a transaction before you are charged.</p></dd>
					<dt>Do other cities offer mobile payment for metered parking? How much do they charge?</dt>
					<dd>
						<p>Many U.S. cities are adopting mobile payment systems for metered parking, including Chicago, San Jose, Louisville, Omaha and Salt Lake City. Typical convenience fees range from 25 to 45 cents.</p></dd>
					<dt>How does ParkDetroit bill me?</dt>
					<dd>
						<p>You can pay for your parking sessions in ParkDetroit by either an individual Credit/Debit card or by funding the ParkDetroit Frequent Prefunded Account.</p>
						<ul>
							<li >Transactions completed using an individual Credit/Debit card will show up on your card statements as individual line items and will be deducted from your account once the parking session is completed.</li>
						</ul>					</dd>
					<dt>Does ParkDetroit require a minimum purchase amount for a transaction?</dt>
					<dd><p>Yes. ParkDetroit requires a minimum purchase of 1 hour.</p> </dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>


				<a id='usingtheapp'></a>
				<h2>Using the ParkDetroit App</h2>
				<dl>
					<dt>How do I know if ParkDetroit is available where I parked?</dt>
					<dd>
						<p>ParkDetroit is currently available in City of Detroit off-street garages and&nbsp; most surface lots. Just look for the ParkDetroit logo on signs in the parking location.</p>					</dd>
					<dt>Can I use ParkDetroit at metered parking outside of the City of Detroit?</dt>
					<dd>
						<p>No. ParkDetroit is only available in the City of Detroit.</p>					</dd>
					<dt>What’s a zone number? How do I locate my zone number?</dt>
					<dd>
						<p>The zone number displayed on the ParkDetroit-logo&nbsp; signs identifies where you are parked. Just look for the ParkDetroit logo on signs in your parking location. . Entering the wrong zone number may result in a ticket.</p>					</dd>
					<dt>Why is it important to use the correct zone number?</dt>
					<dd>
						<p>Each parking location may have different parking restrictions and hours of operation or length of stay.</p>					</dd>
					<dt>If I don’t have my mobile phone with me, can I use a different phone to pay for parking?</dt>
					<dd>
						<p>Yes. Although your phone number, thus your phone, is linked to ParkDetroit for security and verification reasons, you can start another account on a different phone and pay for parking with the new phone number. You may also use your email address to login on a different phone. If you don’t have a mobile phone with you, make a payment at the meter nearest to your vehicle. Additionally, if you’re with someone who has a ParkDetroit account, they can pay for your parking by simply paying for your session and you can repay the favor in the future!</p>					</dd>
					<dt>Why is it that sometimes I can extend parking and sometimes I can’t?</dt>
					<dd>
						<p>You may be unable to extend parking if you are outside the zone’s hours of operation or due to a parking restriction (Such as beyond the maximum parking time limits allowed in that zone). When you purchase parking, you are not permitted to purchase more time than the allowed length of stay. Make sure you check for rates, parking restrictions on the meters and permanent or temporary signage in order to avoid a ticket.</p>
						<p>Like many apps or mobile services, ParkDetroit requires a good cellular or Wi-Fi signal. The connectivity of your personal devices is not under our control, and if you experience failure in wireless service, you will be unable to extend your parking session remotely. In such circumstances, please pay for parking at the meter nearest to your vehicle.</p>					</dd>
					<dt>Can I change my notification alert to something other than 10 minutes?</dt>
					<dd>
						<p>No. At this time, the time period for the notification alert feature cannot be changed.</p>					</dd>
					<dt>I parked using the wrong zone number; can I change it?</dt>
					<dd>
						<p>You cannot change a zone number once your parking session has started, so remember to review screens before confirming your sessions. Make sure you check for rates, parking restrictions on the meter and permanent or temporary signage in order to avoid a ticket.</p>					</dd>
					<dt>How do I know if my parking time was processed?</dt>
					<dd>
						<p>The ParkDetroit app or mobile web session screen shows the start and end times of your parking session. Additionally, a countdown timer will show the remaining amount of time to your current parking session at any point in time.</p>					</dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>


				<a id='accounts'></a>
				<h2>Accounts & Payments</h2>
				<dl>
					<dt>How do I pay for parking using ParkDetroit?</dt>
					<dd><p>You can pay for your parking sessions in ParkDetroit by either an individual Credit/Debit card.</p> <p>Transactions completed using an individual Credit/Debit card will show up on your card statements as individual line items and will be deducted from your account once the parking session is completed.</p></dd>
					<dt>Can I use ParkDetroit without having to set up an account?</dt>
					<dd><p>No. In order to use ParkDetroit, you must set up an account first.</p></dd>
					<dt>Can I use ParkDetroit without having to link my credit or debit card?</dt>
					<dd><p>No. In order to use ParkDetroit, you must link a credit or debit card to your account.</p> </dd>
					<dt>Can I access my parking history? How do I get receipts?</dt>
					<dd>
						<p>Your ParkDetroit transactions are saved and can be accessed in two ways:</p>
						<ol class="list0 nls-None" >
							<li >To email a receipt of a parking session directly from the app, go to Settings and select My Parking History. The app keeps a history of your last 20 parking sessions. Choose a recent session and select Email Receipt. This will send a receipt to the email address associated with the ParkDetroit account.</li>
							<li >To view the entire parking history of your account, you may log in to ParkDetroit.us from a computer and run reports as necessary.</li>
						</ol>					</dd>
					<dt>Is it safe to make payments via ParkDetroit?</dt>
					<dd>
						<p>ParkDetroit is committed to protecting customer information. Your credit card number is encrypted and your information is handled as specified in our privacy policy available here. Insert ParkDetroit Privacy Policy</p>					</dd>
					<dt>How does ParkDetroit use my email?</dt>
					<dd>
						<p>We use your email address only to send you important information regarding your ParkDetroit account.</p>					</dd>
					<dt>How can I deactivate my account?</dt>
					<dd>
						<p>Deactivate your account at any time by visiting ParkDetroit.us. Once you log in, select the Menu (upper left corner icon with three horizontal bars), click on Profile and then click the Deactivate Account button. Be aware that once you deactivate your account, it cannot&nbsp; be reactivated. If you wish to use ParkDetroit again, you will need to create a new account.</p>					</dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>

	

				<a id='troubleshooting'></a>
				<h2>Troubleshooting</h2>
				<dl>
					<dt>The app doesn’t work. I’m not getting notification alerts. It’s slow.</dt>
					<dd>
						<p>Like many apps or mobile services, ParkDetroit requires a good cellular or Wi-Fi signal. If you experience any issues with the app, check your phone’s coverage status and/or Wi-Fi signal first. The connectivity of your personal device is not under our control, and we cannot be responsible for any failure to receive a notification alert or inability to extend a parking session due to failure in wireless service or malfunction with your wireless carrier.</p>
						<p>Also, please be aware that sessions originated from the app, whether on iPhone, iPad or an Android device, receive notifications on the app and on that specific device.</p>
						<p>If you continue to experience problems, let us know by visiting the Menu &gt; Send Bug Report on your app or on ParkDetroit.us and then restart the app. We’ll look into it as soon as possible. Please remember that if you’re unable to pay for parking through ParkDetroit for any reason, you’re still required to pay for metered parking and should do so at the meter nearest to your car .</p>
					</dd>
					<dt>How do I reset my PIN?</dt>
					<dd>
						<p>You create your PIN when you sign up for an account. If you wish to reset your PIN, click on the Reset PIN button on the Login page. You will be required to re-enter your payment card currently on file to verify your identity (we provide the last four digits to help you remember which card you used). After successfully verifying your payment card details, you will be taken to the Create PIN page, at which point you can reset your PIN.</p>
					</dd>
					<dt>Why do I get a “Locked Parking” error message?</dt>
					<dd>
						<p>If you received a “Locked Parking” error message, be aware that we have manually suspended your account due to payment discrepancies. In such cases, please contact us at (Change Number to ParkDetroit Support Number) for more information.</p>
					</dd>
					<dt>Why can’t I add more time to my parking session?</dt>
					<dd>
						<p>If you are unable to add additional time to your parking stay, it is likely that:</p>
						<ol class="list0 nls-None" >
											<li >You have reached the maximum parking time allowed for that location (Please See: Why is it that sometimes I can extend and sometimes I can’t?).</li>
											<li >You do not have to pay as no payment is required (check posted signs for hours of operation).</li>
											<li >You have parked in a restricted location (check posted signs for special restrictions like parking during rush hour).</li>
						</ol>					</dd>
					<dt>Why am I receiving a time out error?</dt>
					<dd>
						<p>ParkDetroit allows 90 seconds to complete a transaction before the system times out. If a time out occurs, simply begin your transaction again.</p>
					</dd>
					<dt>Why didn’t I receive a notification alerting me that my time is about to expire?</dt>
					<dd>
						<p>Like many apps or mobile services, ParkDetroit requires a good cellular or Wi-Fi signal. Check your phone’s coverage status and/or Wi-Fi signal. We cannot be responsible for any failure to get a notification alert or extend parking because of failures in wireless service or due to failure or malfunctions with your wireless carrier.</p>
						<p>Also, go to Menu &gt; Preferences and make sure that the “Remind me when my time is expiring (app notification)” option is selected. Check your phone’s Push Notification settings and make sure that your phone has service. If you are experiencing any problems, let us know by visiting Menu &gt; Send Bug Report on your app or on ParkDetroit.us. We’ll look into as soon as possible.</p>
					</dd>
					<dt>My phone battery has run out and I can’t pay for my parking with ParkDetroit. How can I pay for my parking?</dt>
					<dd>
						<p>Return to the location where your vehicle is parked, and pay at the meter.</p>
					</dd>
					<dt>My name and/or account information has changed. How can I change it?</dt>
					<dd>
						<p>No problem. Using the app or website, visit the Menu and access the options under Settings to change your Profile and/or Payment Details.</p>
					</dd>
					<dt>I have a new phone number. What do I do?</dt>
					<dd>
						<p>If you have a new phone number, you will need to register a new account for that phone number. Deactivate your current account online at ParkDetroit.us and then sign up for a new account.</p>					</dd>
					<dt>Can I add another phone number to my account?</dt>
					<dd>
						<p>No. Each account is connected to a single phone number.</p>
					</dd>
					<dt>I have received multiple charges on my bank account after I used the app. I believe I am a victim of fraud. What can you do?</dt>
					<dd>
						<p>Contact the bank associated with your credit/debit card immediately if you believe you may be a victim of fraud. In addition, please call us immediately at (Insert Passport Helpdesk phone number) so that we can help you determine if the charges are legitimate.</p>
					</dd>
					<dt>I’m trying to create an account but it keeps saying “User Exists.” I’ve never signed up before. Help!</dt>
					<dd>
						<p>Call us at (Insert Passport Helpdesk phone number) so that we can help you sort out the situation.</p>
					</dd>
					<dt>May I get a refund for any unused time?</dt>
					<dd>
						<p>No. Refunds for unused time are not available. Make sure you check for parking restrictions on the pay box and for permanent or temporary signage in order to avoid a ticket.</p>
					</dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>


				<a id='cellphoneusers'></a>
				<h2>For Mobile Browser &amp; Non-smartphone Users</h2>
				<dl>
					<dt>Am I charged for text messages that I receive from ParkDetroit?</dt>
					<dd>
						<p>ParkDetroit does not charge for text messages we send to you, but text messages are subject to standard message and data rates charged by your wireless service provider.</p>					</dd>
					<dt>How can I change my text message preferences?</dt>
					<dd>
						<p>You can manage your text message preferences in the Preferences section on your online account.</p>
					</dd>
					<dt>How do I stop text messages?</dt>
					<dd>
						<p>You can stop text message notifications by visiting the Preferences section on your online account and disabling text messages. Additionally, text STOPTXT to the ParkDetroit number that sends you text messages. Following a request to unsubscribe, you will receive a confirmation message from ParkDetroit confirming that you have been inactivated in our system. Be aware, however, that if you choose not to receive text message alerts, we cannot remind you of when your parking expires.</p>
					</dd>
					<dt>Do I have to sign up for text messages to park?</dt>
					<dd>
						<p>If you purchase parking by calling (Insert IVR number), you must agree to receive text messages regarding your parking transaction. This includes text messages to process your transaction, receipts for your transactions, and parking expiration reminders. If you don’t want to receive text messages you can use our conveniently located kiosks to purchase parking.</p>
						<p>If you purchase parking with ParkDetroit.us either on a desktop or mobile web browser, you can manage your text message preferences for expiration alerts by visiting the Preferences section on your online account. If you choose not to receive text message expiration alerts, we cannot remind you of when your parking expires.</p>
						<p>You do not need to sign up for text messages to use ParkDetroit. However, you will need to receive your account verification code by text message when you sign up for ParkDetroit app.</p>
					</dd>
					<dt>How many text messages will I receive?</dt>
					<dd>
						<p>The number of text messages you receive will depend on the number of parking transactions that you enter into and the method you use to purchase parking. Depending on the method you use to purchase parking, you may get up to eight text messages in relation to your transaction.</p>
					</dd>
					<dt>What else should I know about text messages I may receive from ParkDetroit?</dt>
					<dd>
						<p>Text messages are subject to your wireless carrier’s standard message and data rates. To stop text messages, visit the Preferences section on your online account and disable text messages or text STOPTXT to (Insert IVR number). For help, call (ParkDetroit HelpDesk Phone number). Depending on the method you use to purchase parking you may get up to eight text messages in relation to your transaction. If you don’t want to receive texts please use our conveniently located kiosks to purchase parking.</p>
					</dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>


				<a id='support'></a>
				<h2>Help &amp; Support</h2>
				<dl>
					<dt>How do I get support?</dt>
					<dd>
						<p>Using the app or website, go to Menu &gt; Report a Problem and send us the details of your issue. If you need immediate assistance, please call ParkDetroit at (Insert ParkDetroit Helpdesk phone number) or text HELPME to (IVR system).</p>
					</dd>
				</dl>
				<a class='return-top-link' href='#top'>Back to Top</a>

		</div>
		<!-- End Content -->

	</div>
	<!-- End Row -->

	</div>
<?php get_footer(); ?>